[package]
name = "dake"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.48", features = ["derive"] }
# Local crates
error = { path = "src/crates/error" }
regex = "1.12.1"
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
winnow = "0.7.13"
zstd = "0.13.3"

[workspace]
members = [
    "src/crates/error",
    "src/crates/error-derive",
    "src/crates/rstream",
    "src/crates/rstream-derive",
    "src/crates/sys",
    "src/crates/transaction",
    "src/crates/transaction-derive",
]
